/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Catz' at '8/2/16 11:08 PM' with Gradle 2.14
 *
 * @author Catz, @date 8/2/16 11:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
